### PR TITLE
add google code jam qualification round question

### PR DESCRIPTION
**Pull request by krishnajalan**

### CODE REVIEW

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
In 1st Q solution, you submitted a Python syntax code but file extension is in CPP ? please fix it

**Comment by krishnajalan** [comment]
have had made the required fix.

**Review by krishnajalan — COMMENTED** [review]
fix #22

**Review by krishnajalan — COMMENTED** [review]
fixed #22 and added google code jam questions

**Pull request merged**
